//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS.Certifications.Web.Areas.Security.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Login {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Login() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GS.Certifications.Web.Areas.Security.Pages.Login", typeof(Login).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string Aceptar {
            get {
                return ResourceManager.GetString("Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargar Documento Requerido.
        /// </summary>
        public static string Cargar_Documento_Requerido {
            get {
                return ResourceManager.GetString("Cargar Documento Requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificaciones.
        /// </summary>
        public static string Certificaciones {
            get {
                return ResourceManager.GetString("Certificaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string Contraseña {
            get {
                return ResourceManager.GetString("Contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to el documento actual.
        /// </summary>
        public static string el_documento_actual {
            get {
                return ResourceManager.GetString("el documento actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entorno.
        /// </summary>
        public static string Entorno {
            get {
                return ResourceManager.GetString("Entorno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo.
        /// </summary>
        public static string Grupo {
            get {
                return ResourceManager.GetString("Grupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha finalizado la sesión. Vuelva a ingresar..
        /// </summary>
        public static string Ha_finalizado_la_sesión__Vuelva_a_ingresar_ {
            get {
                return ResourceManager.GetString("Ha finalizado la sesión. Vuelva a ingresar.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar.
        /// </summary>
        public static string Ingresar {
            get {
                return ResourceManager.GetString("Ingresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar contraseña.
        /// </summary>
        public static string Ingresar_contraseña {
            get {
                return ResourceManager.GetString("Ingresar contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar email para recuperar contraseña.
        /// </summary>
        public static string Ingresar_email_para_recuperar_contraseña {
            get {
                return ResourceManager.GetString("Ingresar email para recuperar contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar usuario o email.
        /// </summary>
        public static string Ingresar_usuario_o_email {
            get {
                return ResourceManager.GetString("Ingresar usuario o email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar.
        /// </summary>
        public static string IngresarAlSistema {
            get {
                return ResourceManager.GetString("IngresarAlSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingreso al sistema.
        /// </summary>
        public static string Ingreso_al_sistema {
            get {
                return ResourceManager.GetString("Ingreso al sistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario o email.
        /// </summary>
        public static string Nombre_de_usuario_o_email {
            get {
                return ResourceManager.GetString("Nombre de usuario o email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olvidé mi contraseña.
        /// </summary>
        public static string Olvidé_mi_contraseña {
            get {
                return ResourceManager.GetString("Olvidé mi contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olvidé mi contraseña.
        /// </summary>
        public static string OlvideMiContraseña {
            get {
                return ResourceManager.GetString("OlvideMiContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para continuar, por favor seleccioná el archivo para.
        /// </summary>
        public static string Para_continuar__por_favor_seleccioná_el_archivo_para {
            get {
                return ResourceManager.GetString("Para continuar, por favor seleccioná el archivo para", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal de Certificaciones.
        /// </summary>
        public static string Portal_de_Certificaciones {
            get {
                return ResourceManager.GetString("Portal de Certificaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido a Boarding.coex.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario o Email.
        /// </summary>
        public static string Usuario_o_Email {
            get {
                return ResourceManager.GetString("Usuario o Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver al inicio.
        /// </summary>
        public static string Volver_al_inicio {
            get {
                return ResourceManager.GetString("Volver al inicio", resourceCulture);
            }
        }
    }
}
