//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS.Certifications.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SupplierDomainResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SupplierDomainResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GS.Certifications.Domain.Resources.SupplierDomainResources", typeof(SupplierDomainResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se debe indicar el idioma de la reserva..
        /// </summary>
        internal static string CultureIsEmpty {
            get {
                return ResourceManager.GetString("CultureIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La reserva no puede quedar sin item/s..
        /// </summary>
        internal static string EmptyBooking {
            get {
                return ResourceManager.GetString("EmptyBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El producto reservado indica {0} item/s, pero tiene {1} pasajero/s asociados..
        /// </summary>
        internal static string LinkedPassengersDoNotMatchRowQuantity {
            get {
                return ResourceManager.GetString("LinkedPassengersDoNotMatchRowQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El producto reservado indica {0} item/s, pero tiene {1} vehículo/s asociados..
        /// </summary>
        internal static string LinkedVehiclesDoNotMatchRowQuantity {
            get {
                return ResourceManager.GetString("LinkedVehiclesDoNotMatchRowQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal de Socios.
        /// </summary>
        internal static string Portal_de_Socios {
            get {
                return ResourceManager.GetString("Portal de Socios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se debe indicar el Punto de Venta de la reserva..
        /// </summary>
        internal static string SalePointIsEmpty {
            get {
                return ResourceManager.GetString("SalePointIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El email del comprador {0} es inválido..
        /// </summary>
        internal static string WrongBuyerEmail {
            get {
                return ResourceManager.GetString("WrongBuyerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cantidad de pasajeros de tipo {0} no coincide con el tipo de los pasajeros relacionados..
        /// </summary>
        internal static string WrongVariantPassengers {
            get {
                return ResourceManager.GetString("WrongVariantPassengers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cantidad de vehículos de tipo {0} no coincide con el tipo de los vehículos relacionados..
        /// </summary>
        internal static string WrongVariantVehicles {
            get {
                return ResourceManager.GetString("WrongVariantVehicles", resourceCulture);
            }
        }
    }
}
