//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socios.Web.Areas.Security.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Login {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Login() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Socios.Web.Areas.Security.Pages.Login", typeof(Login).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string Aceptar {
            get {
                return ResourceManager.GetString("Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algo no salió bien al enviar la notificación de la recuperación de contraseña. Intentá más tarde o consultá a soporte..
        /// </summary>
        public static string Algo_no_salió_bien_al_enviar_la_notificación_de_la_recuperación_de_contraseña__Intentá_más_tarde_o_consultá_a_soporte_ {
            get {
                return ResourceManager.GetString("Algo no salió bien al enviar la notificación de la recuperación de contraseña. In" +
                        "tentá más tarde o consultá a soporte.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string Contraseña {
            get {
                return ResourceManager.GetString("Contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar un usuario o email..
        /// </summary>
        public static string Debe_ingresar_un_usuario_o_email_ {
            get {
                return ResourceManager.GetString("Debe ingresar un usuario o email.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no existe. Complete con un email válido..
        /// </summary>
        public static string El_usuario_no_existe__Complete_con_un_email_válido_ {
            get {
                return ResourceManager.GetString("El usuario no existe. Complete con un email válido.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entorno.
        /// </summary>
        public static string Entorno {
            get {
                return ResourceManager.GetString("Entorno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo.
        /// </summary>
        public static string Grupo {
            get {
                return ResourceManager.GetString("Grupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha finalizado la sesión.
        /// </summary>
        public static string Ha_finalizado_la_sesión {
            get {
                return ResourceManager.GetString("Ha finalizado la sesión", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha finalizado la sesión. Vuelva a ingresar..
        /// </summary>
        public static string Ha_finalizado_la_sesión__Vuelva_a_ingresar_ {
            get {
                return ResourceManager.GetString("Ha finalizado la sesión. Vuelva a ingresar.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar.
        /// </summary>
        public static string Ingresar {
            get {
                return ResourceManager.GetString("Ingresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar contraseña.
        /// </summary>
        public static string Ingresar_contraseña {
            get {
                return ResourceManager.GetString("Ingresar contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar email para recuperar contraseña.
        /// </summary>
        public static string Ingresar_email_para_recuperar_contraseña {
            get {
                return ResourceManager.GetString("Ingresar email para recuperar contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar usuario o email.
        /// </summary>
        public static string Ingresar_usuario_o_email {
            get {
                return ResourceManager.GetString("Ingresar usuario o email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingreso al sistema.
        /// </summary>
        public static string Ingreso_al_sistema {
            get {
                return ResourceManager.GetString("Ingreso al sistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario o email.
        /// </summary>
        public static string Nombre_de_usuario_o_email {
            get {
                return ResourceManager.GetString("Nombre de usuario o email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olvidé mi contraseña.
        /// </summary>
        public static string Olvidé_mi_contraseña {
            get {
                return ResourceManager.GetString("Olvidé mi contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to por favor revise su casilla de correo..
        /// </summary>
        public static string por_favor_revise_su_casilla_de_correo_ {
            get {
                return ResourceManager.GetString("por favor revise su casilla de correo.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal de Proveedores de.
        /// </summary>
        public static string Portal_de_Proveedores_de {
            get {
                return ResourceManager.GetString("Portal de Proveedores de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal de Socios.
        /// </summary>
        public static string Portal_de_Socios {
            get {
                return ResourceManager.GetString("Portal de Socios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha enviado un email a.
        /// </summary>
        public static string Se_ha_enviado_un_email_a {
            get {
                return ResourceManager.GetString("Se ha enviado un email a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selección de Socio.
        /// </summary>
        public static string Selección_de_Socio {
            get {
                return ResourceManager.GetString("Selección de Socio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione Socio.
        /// </summary>
        public static string Seleccione_Socio {
            get {
                return ResourceManager.GetString("Seleccione Socio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un Socio.
        /// </summary>
        public static string Seleccione_un_Socio {
            get {
                return ResourceManager.GetString("Seleccione un Socio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socio.
        /// </summary>
        public static string Socio {
            get {
                return ResourceManager.GetString("Socio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido a Boarding.coex.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario o clave incorrecta..
        /// </summary>
        public static string Usuario_o_clave_incorrecta_ {
            get {
                return ResourceManager.GetString("Usuario o clave incorrecta.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario o Email.
        /// </summary>
        public static string Usuario_o_Email {
            get {
                return ResourceManager.GetString("Usuario o Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver al inicio.
        /// </summary>
        public static string Volver_al_inicio {
            get {
                return ResourceManager.GetString("Volver al inicio", resourceCulture);
            }
        }
    }
}
