using GSF.Infrastructure.Persistence.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using GS.Certifications.Domain.Entities.Comprobantes;

namespace GS.Certifications.Infrastructure.Persistence.Configurations.Comprobantes;

public class ComprobanteTipoConfiguration : BaseFixedEntityInt16Configuration<ComprobanteTipo>
{
    protected override void ConfigureEntity(EntityTypeBuilder<ComprobanteTipo> builder)
    {
        builder.ToTable("com_ComprobanteTipos");

        builder.Property(i => i.CodigoArca).IsRequired().HasMaxLength(100);
        builder.Property(i => i.Descripcion).IsRequired().HasMaxLength(500);
        builder.Property(i => i.DescAbreviada).HasMaxLength(500);
        builder.Property(i => i.NombreComprobante).HasMaxLength(250);
        builder.Property(i => i.Letra).HasMaxLength(10);
        builder.Property(i => i.CodigoExterno).HasMaxLength(100);
    }

    protected override void LoadSeedingData()
    {
        SeedingData.AddRange(
            new ComprobanteTipo() { Idm = ComprobanteTipo.FACTURA_A, Descripcion = "Factura A", CodigoArca = ComprobanteTipo.FACTURA_A_CODIGO_AFIP, Letra = ComprobanteTipo.FACTURA_A_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = "FC-A" },
        new ComprobanteTipo() { Idm = ComprobanteTipo.NOTA_DEBITO_A, Descripcion = "Nota de Débito A", CodigoArca = ComprobanteTipo.NOTA_DEBITO_A_CODIGO_AFIP, Letra = ComprobanteTipo.NOTA_DEBITO_A_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = "ND-A" },
        new ComprobanteTipo() { Idm = ComprobanteTipo.NOTA_CREDITO_A, Descripcion = "Nota de Crédito A", CodigoArca = ComprobanteTipo.NOTA_CREDITO_A_CODIGO_AFIP, Letra = ComprobanteTipo.NOTA_CREDITO_A_CODIGO_LETRA, TipoOperacion = -1, DescAbreviada = "NC-A" },
        new ComprobanteTipo() { Idm = ComprobanteTipo.RECIBO_A, Descripcion = "Recibo A", CodigoArca = ComprobanteTipo.RECIBO_A_CODIGO_AFIP, Letra = ComprobanteTipo.RECIBO_A_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = "RC-A" },
        new ComprobanteTipo() { Idm = ComprobanteTipo.NOTA_VENTA_CONTADO_A, Descripcion = "Nota de venta al contado A", CodigoArca = ComprobanteTipo.NOTA_VENTA_CONTADO_A_CODIGO_AFIP, Letra = ComprobanteTipo.NOTA_VENTA_CONTADO_A_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = "NV-A" },
        new ComprobanteTipo() { Idm = ComprobanteTipo.FACTURA_B, Descripcion = "Factura B", CodigoArca = ComprobanteTipo.FACTURA_B_CODIGO_AFIP, Letra = ComprobanteTipo.FACTURA_B_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = "FC-B" },
        new ComprobanteTipo() { Idm = ComprobanteTipo.NOTA_DEBITO_B, Descripcion = "Nota de Débito B", CodigoArca = ComprobanteTipo.NOTA_DEBITO_B_CODIGO_AFIP, Letra = ComprobanteTipo.NOTA_DEBITO_B_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = "ND-B" },
        new ComprobanteTipo() { Idm = ComprobanteTipo.NOTA_CREDITO_B, Descripcion = "Nota de Crédito B", CodigoArca = ComprobanteTipo.NOTA_CREDITO_B_CODIGO_AFIP, Letra = ComprobanteTipo.NOTA_CREDITO_B_CODIGO_LETRA, TipoOperacion = -1, DescAbreviada = "NC-B" },
        new ComprobanteTipo() { Idm = ComprobanteTipo.RECIBO_B, Descripcion = "Recibo B", CodigoArca = ComprobanteTipo.RECIBO_B_CODIGO_AFIP, Letra = ComprobanteTipo.RECIBO_B_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = "RC-B" },
        new ComprobanteTipo() { Idm = ComprobanteTipo.NOTA_VENTA_CONTADO_B, Descripcion = "Nota de venta al contado B", CodigoArca = ComprobanteTipo.NOTA_VENTA_CONTADO_B_CODIGO_AFIP, Letra = ComprobanteTipo.NOTA_VENTA_CONTADO_B_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = "NV-B" },
        new ComprobanteTipo() { Idm = ComprobanteTipo.COMPROBANTE_A_CUMPLE_3419, Descripcion = "Comprobante A que cumple con la R.G. N° 3419", CodigoArca = ComprobanteTipo.COMPROBANTE_A_CUMPLE_3419_CODIGO_AFIP, Letra = ComprobanteTipo.COMPROBANTE_A_CUMPLE_3419_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = null },
        new ComprobanteTipo() { Idm = ComprobanteTipo.COMPROBANTE_B_CUMPLE_3419, Descripcion = "Comprobante B que cumple con la R.G. N° 3419", CodigoArca = ComprobanteTipo.COMPROBANTE_B_CUMPLE_3419_CODIGO_AFIP, Letra = ComprobanteTipo.COMPROBANTE_B_CUMPLE_3419_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = null },
        new ComprobanteTipo() { Idm = ComprobanteTipo.CUENTA_VENTA_LIQUIDO_A, Descripcion = "Cuenta de venta y líquido producto A", CodigoArca = ComprobanteTipo.CUENTA_VENTA_LIQUIDO_A_CODIGO_AFIP, Letra = ComprobanteTipo.CUENTA_VENTA_LIQUIDO_A_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = null },
        new ComprobanteTipo() { Idm = ComprobanteTipo.CUENTA_VENTA_LIQUIDO_B, Descripcion = "Cuenta de venta y líquido producto B", CodigoArca = ComprobanteTipo.CUENTA_VENTA_LIQUIDO_B_CODIGO_AFIP, Letra = ComprobanteTipo.CUENTA_VENTA_LIQUIDO_B_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = null },
        new ComprobanteTipo() { Idm = ComprobanteTipo.LIQUIDACION_A, Descripcion = "Liquidación A", CodigoArca = ComprobanteTipo.LIQUIDACION_A_CODIGO_AFIP, Letra = ComprobanteTipo.LIQUIDACION_A_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = "LG-A" },
        new ComprobanteTipo() { Idm = ComprobanteTipo.LIQUIDACION_B, Descripcion = "Liquidación B", CodigoArca = ComprobanteTipo.LIQUIDACION_B_CODIGO_AFIP, Letra = ComprobanteTipo.LIQUIDACION_B_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = "LG-B" },
        new ComprobanteTipo() { Idm = ComprobanteTipo.FACTURA_C, Descripcion = "Factura C", CodigoArca = ComprobanteTipo.FACTURA_C_CODIGO_AFIP, Letra = ComprobanteTipo.FACTURA_C_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = "FC-C" },
        new ComprobanteTipo() { Idm = ComprobanteTipo.DOCUMENTO_ADUANERO, Descripcion = "Documento aduanero", CodigoArca = ComprobanteTipo.DOCUMENTO_ADUANERO_CODIGO_AFIP, Letra = ComprobanteTipo.DOCUMENTO_ADUANERO_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = "DA-A" },
        new ComprobanteTipo() { Idm = ComprobanteTipo.RECIBO_C, Descripcion = "Recibo C", CodigoArca = ComprobanteTipo.RECIBO_C_CODIGO_AFIP, Letra = ComprobanteTipo.RECIBO_C_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = "RC-C" },
        new ComprobanteTipo() { Idm = ComprobanteTipo.NOTA_VENTA_CONTADO_C, Descripcion = "Nota de venta al contado C", CodigoArca = ComprobanteTipo.NOTA_VENTA_CONTADO_C_CODIGO_AFIP, Letra = ComprobanteTipo.NOTA_VENTA_CONTADO_C_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = null },
        new ComprobanteTipo() { Idm = ComprobanteTipo.FACTURA_E, Descripcion = "Factura E", CodigoArca = ComprobanteTipo.FACTURA_E_CODIGO_AFIP, Letra = ComprobanteTipo.FACTURA_E_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = "FC-E" },
        new ComprobanteTipo() { Idm = ComprobanteTipo.NOTA_DEBITO_E, Descripcion = "Nota de Débito E", CodigoArca = ComprobanteTipo.NOTA_DEBITO_E_CODIGO_AFIP, Letra = ComprobanteTipo.NOTA_DEBITO_E_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = "ND-E" },
        new ComprobanteTipo() { Idm = ComprobanteTipo.NOTA_CREDITO_E, Descripcion = "Nota de Crédito E", CodigoArca = ComprobanteTipo.NOTA_CREDITO_E_CODIGO_AFIP, Letra = ComprobanteTipo.NOTA_CREDITO_E_CODIGO_LETRA, TipoOperacion = -1, DescAbreviada = "NC-E" },
        new ComprobanteTipo() { Idm = ComprobanteTipo.PERMISO_EXPORT_SIMPLIFICADO, Descripcion = "Facturas - Permiso Export simplificado - Dto.855/97", CodigoArca = ComprobanteTipo.PERMISO_EXPORT_SIMPLIFICADO_CODIGO_AFIP, Letra = ComprobanteTipo.PERMISO_EXPORT_SIMPLIFICADO_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = null },
        new ComprobanteTipo() { Idm = ComprobanteTipo.COMPRA_BIENES_USADOS, Descripcion = "Comprobantes de compra de bienes usados", CodigoArca = ComprobanteTipo.COMPRA_BIENES_USADOS_CODIGO_AFIP, Letra = ComprobanteTipo.COMPRA_BIENES_USADOS_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = null },
        new ComprobanteTipo() { Idm = ComprobanteTipo.COMPROBANTE_A_RG_1415, Descripcion = "Comprob A del Anexo I, Apartado A, inc.f), RG 1415", CodigoArca = ComprobanteTipo.COMPROBANTE_A_RG_1415_CODIGO_AFIP, Letra = ComprobanteTipo.COMPROBANTE_A_RG_1415_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = null },
        new ComprobanteTipo() { Idm = ComprobanteTipo.COMPROBANTE_B_RG_1415, Descripcion = "Comprob B del Anexo I, Apartado A, inc.f), RG 1415", CodigoArca = ComprobanteTipo.COMPROBANTE_B_RG_1415_CODIGO_AFIP, Letra = ComprobanteTipo.COMPROBANTE_B_RG_1415_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = null },
        new ComprobanteTipo() { Idm = ComprobanteTipo.COMPROBANTE_C_RG_1415, Descripcion = "Comprob C del Anexo I, Apartado A, inc.f), RG 1415", CodigoArca = ComprobanteTipo.COMPROBANTE_C_RG_1415_CODIGO_AFIP, Letra = ComprobanteTipo.COMPROBANTE_C_RG_1415_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = null },
        new ComprobanteTipo() { Idm = ComprobanteTipo.NOTA_DEBITO_RG_1415, Descripcion = "Notas de Débito o doc equiv que cumplan con la RG 1415", CodigoArca = ComprobanteTipo.NOTA_DEBITO_RG_1415_CODIGO_AFIP, Letra = ComprobanteTipo.NOTA_DEBITO_RG_1415_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = null },
        new ComprobanteTipo() { Idm = ComprobanteTipo.NOTA_CREDITO_RG_1415, Descripcion = "Notas de Crédito o doc equiv que cumplan con la RG 1415", CodigoArca = ComprobanteTipo.NOTA_CREDITO_RG_1415_CODIGO_AFIP, Letra = ComprobanteTipo.NOTA_CREDITO_RG_1415_CODIGO_LETRA, TipoOperacion = -1, DescAbreviada = null },
        new ComprobanteTipo() { Idm = ComprobanteTipo.OTRO_COMPROBANTES_A_RG_1415, Descripcion = "Otros comprob A que cumplan con la R.G 1415", CodigoArca = ComprobanteTipo.OTRO_COMPROBANTES_A_RG_1415_CODIGO_AFIP, Letra = ComprobanteTipo.OTRO_COMPROBANTES_A_RG_1415_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = null },
        new ComprobanteTipo() { Idm = ComprobanteTipo.OTRO_COMPROBANTES_B_RG_1415, Descripcion = "Otros comprob B que cumplan con la R.G 1415", CodigoArca = ComprobanteTipo.OTRO_COMPROBANTES_B_RG_1415_CODIGO_AFIP, Letra = ComprobanteTipo.OTRO_COMPROBANTES_B_RG_1415_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = null },
        new ComprobanteTipo() { Idm = ComprobanteTipo.OTRO_COMPROBANTES_C_RG_1415, Descripcion = "Otros comprob C que cumplan con la R.G 1415", CodigoArca = ComprobanteTipo.OTRO_COMPROBANTES_C_RG_1415_CODIGO_AFIP, Letra = ComprobanteTipo.OTRO_COMPROBANTES_C_RG_1415_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = null },
        new ComprobanteTipo() { Idm = ComprobanteTipo.FACTURA_M, Descripcion = "Facturas M", CodigoArca = ComprobanteTipo.FACTURA_M_CODIGO_AFIP, Letra = ComprobanteTipo.FACTURA_M_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = "FC-M" },
        new ComprobanteTipo() { Idm = ComprobanteTipo.NOTA_DEBITO_M, Descripcion = "Notas de Débito M", CodigoArca = ComprobanteTipo.NOTA_DEBITO_M_CODIGO_AFIP, Letra = ComprobanteTipo.NOTA_DEBITO_M_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = "ND-M" },
        new ComprobanteTipo() { Idm = ComprobanteTipo.NOTA_CREDITO_M, Descripcion = "Notas de Crédito M", CodigoArca = ComprobanteTipo.NOTA_CREDITO_M_CODIGO_AFIP, Letra = ComprobanteTipo.NOTA_CREDITO_M_CODIGO_LETRA, TipoOperacion = -1, DescAbreviada = "NC-M" },
        new ComprobanteTipo() { Idm = ComprobanteTipo.RECIBO_M, Descripcion = "Recibos M", CodigoArca = ComprobanteTipo.RECIBO_M_CODIGO_AFIP, Letra = ComprobanteTipo.RECIBO_M_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = "RC-M" },
        new ComprobanteTipo() { Idm = ComprobanteTipo.NOTA_VENTA_CONTADO_M, Descripcion = "Notas de Venta al contado M", CodigoArca = ComprobanteTipo.NOTA_VENTA_CONTADO_M_CODIGO_AFIP, Letra = ComprobanteTipo.NOTA_VENTA_CONTADO_M_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = "NV-M" },
        new ComprobanteTipo() { Idm = ComprobanteTipo.COMPROBANTE_M_RG_1415, Descripcion = "Comprobantes M del Anexo I, Ap A, inc.f), RG 1415", CodigoArca = ComprobanteTipo.COMPROBANTE_M_RG_1415_CODIGO_AFIP, Letra = ComprobanteTipo.COMPROBANTE_M_RG_1415_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = null },
        new ComprobanteTipo() { Idm = ComprobanteTipo.OTRO_COMPROBANTE_M_RG_1415, Descripcion = "Otros comprob M que cumplan con la RG 1415", CodigoArca = ComprobanteTipo.OTRO_COMPROBANTE_M_RG_1415_CODIGO_AFIP, Letra = ComprobanteTipo.OTRO_COMPROBANTE_M_RG_1415_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = null },
        new ComprobanteTipo() { Idm = ComprobanteTipo.CUENTA_VENTA_LIQUIDO_M, Descripcion = "Cuenta de Venta y Líquido producto M", CodigoArca = ComprobanteTipo.CUENTA_VENTA_LIQUIDO_M_CODIGO_AFIP, Letra = ComprobanteTipo.CUENTA_VENTA_LIQUIDO_M_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = null },
        new ComprobanteTipo() { Idm = ComprobanteTipo.LIQUIDACION_M, Descripcion = "Liquidación M", CodigoArca = ComprobanteTipo.LIQUIDACION_M_CODIGO_AFIP, Letra = ComprobanteTipo.LIQUIDACION_M_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = "LG-M" },
        new ComprobanteTipo() { Idm = ComprobanteTipo.CUENTA_VENTA_LIQUIDO_C, Descripcion = "Cuenta de Venta y Líquido producto C", CodigoArca = ComprobanteTipo.CUENTA_VENTA_LIQUIDO_C_CODIGO_AFIP, Letra = ComprobanteTipo.CUENTA_VENTA_LIQUIDO_C_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = "LIPC" },
        new ComprobanteTipo() { Idm = ComprobanteTipo.LIQUIDACION_C, Descripcion = "Liquidación C", CodigoArca = ComprobanteTipo.LIQUIDACION_C_CODIGO_AFIP, Letra = ComprobanteTipo.LIQUIDACION_C_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = "LG-C" },
        new ComprobanteTipo() { Idm = ComprobanteTipo.COMPROBANTE_DIARIO_CIERRE, Descripcion = "Comprobante diario de cierre (zeta)", CodigoArca = ComprobanteTipo.COMPROBANTE_DIARIO_CIERRE_CODIGO_AFIP, Letra = ComprobanteTipo.COMPROBANTE_DIARIO_CIERRE_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = null },
        new ComprobanteTipo() { Idm = ComprobanteTipo.TIQUE_FACTURA_A, Descripcion = "Tique-Factura A", CodigoArca = ComprobanteTipo.TIQUE_FACTURA_A_CODIGO_AFIP, Letra = ComprobanteTipo.TIQUE_FACTURA_A_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = "TF-A" },
        new ComprobanteTipo() { Idm = ComprobanteTipo.TIQUE_FACTURA_B, Descripcion = "Tique-Factura B", CodigoArca = ComprobanteTipo.TIQUE_FACTURA_B_CODIGO_AFIP, Letra = ComprobanteTipo.TIQUE_FACTURA_B_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = "TF-B" },
        new ComprobanteTipo() { Idm = ComprobanteTipo.TIQUE, Descripcion = "Tique", CodigoArca = ComprobanteTipo.TIQUE_CODIGO_AFIP, Letra = ComprobanteTipo.TIQUE_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = "T" },
        new ComprobanteTipo() { Idm = ComprobanteTipo.COMPROBANTE_FACTURA_SERVICIOS_PUBLICOS, Descripcion = "Comprobante/Factura de servicios públicos", CodigoArca = ComprobanteTipo.COMPROBANTE_FACTURA_SERVICIOS_PUBLICOS_CODIGO_AFIP, Letra = ComprobanteTipo.COMPROBANTE_FACTURA_SERVICIOS_PUBLICOS_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = null },
        new ComprobanteTipo() { Idm = ComprobanteTipo.NOTA_CREDITO_SERVICIOS_PUBLICOS, Descripcion = "Nota de Crédito - servicios públicos", CodigoArca = ComprobanteTipo.NOTA_CREDITO_SERVICIOS_PUBLICOS_CODIGO_AFIP, Letra = ComprobanteTipo.NOTA_CREDITO_SERVICIOS_PUBLICOS_CODIGO_LETRA, TipoOperacion = -1, DescAbreviada = null },
        new ComprobanteTipo() { Idm = ComprobanteTipo.NOTA_DEBITO_SERVICIOS_PUBLICOS, Descripcion = "Nota de Débito - servicios públicos", CodigoArca = ComprobanteTipo.NOTA_DEBITO_SERVICIOS_PUBLICOS_CODIGO_AFIP, Letra = ComprobanteTipo.NOTA_DEBITO_SERVICIOS_PUBLICOS_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = null },
        new ComprobanteTipo() { Idm = ComprobanteTipo.OTRO_COMPROBANTE_SERVICIOS_EXTERIOR, Descripcion = "Otros comp - servicios del exterior", CodigoArca = ComprobanteTipo.OTRO_COMPROBANTE_SERVICIOS_EXTERIOR_CODIGO_AFIP, Letra = ComprobanteTipo.OTRO_COMPROBANTE_SERVICIOS_EXTERIOR_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = null },
        new ComprobanteTipo() { Idm = ComprobanteTipo.OTRO_COMPROBANTE_DOC_EXCEPTUADOS_NOTA_DEBITO, Descripcion = "Otros comp - doc exceptuados - Nota de Débito", CodigoArca = ComprobanteTipo.OTRO_COMPROBANTE_DOC_EXCEPTUADOS_NOTA_DEBITO_CODIGO_AFIP, Letra = ComprobanteTipo.OTRO_COMPROBANTE_DOC_EXCEPTUADOS_NOTA_DEBITO_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = null },
        new ComprobanteTipo() { Idm = ComprobanteTipo.OTRO_COMPROBANTE_DOC_EXCEPTUADOS_NOTA_CREDITO, Descripcion = "Otros comp - doc exceptuados - Nota de Crédito", CodigoArca = ComprobanteTipo.OTRO_COMPROBANTE_DOC_EXCEPTUADOS_NOTA_CREDITO_CODIGO_AFIP, Letra = ComprobanteTipo.OTRO_COMPROBANTE_DOC_EXCEPTUADOS_NOTA_CREDITO_CODIGO_LETRA, TipoOperacion = -1, DescAbreviada = null },
        new ComprobanteTipo() { Idm = ComprobanteTipo.AJ_CONTABLES_QUE_INCREMENTAN_DEBITO_FISCAL, Descripcion = "Aj contables que incrementan el débito fiscal", CodigoArca = ComprobanteTipo.AJ_CONTABLES_QUE_INCREMENTAN_DEBITO_FISCAL_CODIGO_AFIP, Letra = ComprobanteTipo.AJ_CONTABLES_QUE_INCREMENTAN_DEBITO_FISCAL_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = null },
        new ComprobanteTipo() { Idm = ComprobanteTipo.AJ_CONTABLES_QUE_DISMINUYEN_DEBITO_FISCAL, Descripcion = "Aj contables que disminuyen el débito fiscal", CodigoArca = ComprobanteTipo.AJ_CONTABLES_QUE_DISMINUYEN_DEBITO_FISCAL_CODIGO_AFIP, Letra = ComprobanteTipo.AJ_CONTABLES_QUE_DISMINUYEN_DEBITO_FISCAL_CODIGO_LETRA, TipoOperacion = -1, DescAbreviada = null },
new ComprobanteTipo() { Idm = ComprobanteTipo.AJ_CONTABLES_QUE_INCREMENTAN_CREDITO_FISCAL, Descripcion = "Aj contables que incrementan el crédito fiscal", CodigoArca = ComprobanteTipo.AJ_CONTABLES_QUE_INCREMENTAN_CREDITO_FISCAL_CODIGO_AFIP, Letra = ComprobanteTipo.AJ_CONTABLES_QUE_INCREMENTAN_CREDITO_FISCAL_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = null },
new ComprobanteTipo() { Idm = ComprobanteTipo.AJ_CONTABLES_QUE_DISMINUYEN_CREDITO_FISCAL, Descripcion = "Aj contables que disminuyen el crédito fiscal", CodigoArca = ComprobanteTipo.AJ_CONTABLES_QUE_DISMINUYEN_CREDITO_FISCAL_CODIGO_AFIP, Letra = ComprobanteTipo.AJ_CONTABLES_QUE_DISMINUYEN_CREDITO_FISCAL_CODIGO_LETRA, TipoOperacion = -1, DescAbreviada = null },
new ComprobanteTipo() { Idm = ComprobanteTipo.NOTA_CREDITO_C, Descripcion = "Notas de Crédito C", CodigoArca = ComprobanteTipo.NOTA_CREDITO_C_CODIGO_AFIP, Letra = ComprobanteTipo.NOTA_CREDITO_C_CODIGO_LETRA, TipoOperacion = -1, DescAbreviada = "NC-C" },
new ComprobanteTipo() { Idm = ComprobanteTipo.NOTA_DEBITO_C, Descripcion = "Notas de Débito C", CodigoArca = ComprobanteTipo.NOTA_DEBITO_C_CODIGO_AFIP, Letra = ComprobanteTipo.NOTA_DEBITO_C_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = "ND-C" },
new ComprobanteTipo() { Idm = ComprobanteTipo.NOTA_CREDITO_CDD_A, Descripcion = "Notas de Crédito sobre CDD A", CodigoArca = ComprobanteTipo.NOTA_CREDITO_CDD_A_CODIGO_AFIP, Letra = ComprobanteTipo.NOTA_CREDITO_CDD_A_CODIGO_LETRA, TipoOperacion = 0, DescAbreviada = "NCCA" },
new ComprobanteTipo() { Idm = ComprobanteTipo.NOTA_CREDITO_CDD_B, Descripcion = "Notas de Crédito sobre CDD B", CodigoArca = ComprobanteTipo.NOTA_CREDITO_CDD_B_CODIGO_AFIP, Letra = ComprobanteTipo.NOTA_CREDITO_CDD_B_CODIGO_LETRA, TipoOperacion = 0, DescAbreviada = "NCCB" },
new ComprobanteTipo() { Idm = ComprobanteTipo.RECIBO, Descripcion = "Recibo", CodigoArca = ComprobanteTipo.RECIBO_CODIGO_AFIP, Letra = ComprobanteTipo.RECIBO_CODIGO_LETRA, TipoOperacion = 0, DescAbreviada = "RECI" },
new ComprobanteTipo() { Idm = ComprobanteTipo.ACCOR, Descripcion = "ACCOR", CodigoArca = ComprobanteTipo.ACCOR_CODIGO_AFIP, Letra = ComprobanteTipo.ACCOR_CODIGO_LETRA, TipoOperacion = 0, DescAbreviada = null },
new ComprobanteTipo() { Idm = ComprobanteTipo.REMITO, Descripcion = "Remito", CodigoArca = ComprobanteTipo.REMITO_CODIGO_AFIP, Letra = ComprobanteTipo.REMITO_CODIGO_LETRA, TipoOperacion = 0, DescAbreviada = "RMTO" },
new ComprobanteTipo() { Idm = ComprobanteTipo.FCE_FACTURA_MIPYMES_A, Descripcion = "FCE Factura MiPyMEs A", CodigoArca = ComprobanteTipo.FCE_FACTURA_MIPYMES_A_CODIGO_AFIP, Letra = ComprobanteTipo.FCE_FACTURA_MIPYMES_A_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = "FCEA" },
new ComprobanteTipo() { Idm = ComprobanteTipo.FCE_NOTA_DEBITO_MIPYMES_A, Descripcion = "FCE Nota de Débito MiPyMEs A", CodigoArca = ComprobanteTipo.FCE_NOTA_DEBITO_MIPYMES_A_CODIGO_AFIP, Letra = ComprobanteTipo.FCE_NOTA_DEBITO_MIPYMES_A_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = "NDEA" },
new ComprobanteTipo() { Idm = ComprobanteTipo.FCE_NOTA_CREDITO_MIPYMES_A, Descripcion = "FCE Nota de Crédito MiPyMEs A", CodigoArca = ComprobanteTipo.FCE_NOTA_CREDITO_MIPYMES_A_CODIGO_AFIP, Letra = ComprobanteTipo.FCE_NOTA_CREDITO_MIPYMES_A_CODIGO_LETRA, TipoOperacion = -1, DescAbreviada = "NCEA" },
new ComprobanteTipo() { Idm = ComprobanteTipo.FCE_FACTURA_MIPYMES_B, Descripcion = "FCE Factura MiPyMEs B", CodigoArca = ComprobanteTipo.FCE_FACTURA_MIPYMES_B_CODIGO_AFIP, Letra = ComprobanteTipo.FCE_FACTURA_MIPYMES_B_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = "FCEB" },
new ComprobanteTipo() { Idm = ComprobanteTipo.FCE_NOTA_DEBITO_MIPYMES_B, Descripcion = "FCE Nota de Débito MiPyMEs B", CodigoArca = ComprobanteTipo.FCE_NOTA_DEBITO_MIPYMES_B_CODIGO_AFIP, Letra = ComprobanteTipo.FCE_NOTA_DEBITO_MIPYMES_B_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = "NDEB" },
new ComprobanteTipo() { Idm = ComprobanteTipo.FCE_NOTA_CREDITO_MIPYMES_B, Descripcion = "FCE Nota de Crédito MiPyMEs B", CodigoArca = ComprobanteTipo.FCE_NOTA_CREDITO_MIPYMES_B_CODIGO_AFIP, Letra = ComprobanteTipo.FCE_NOTA_CREDITO_MIPYMES_B_CODIGO_LETRA, TipoOperacion = -1, DescAbreviada = "NCEB" },
new ComprobanteTipo() { Idm = ComprobanteTipo.FCE_FACTURA_MIPYMES_C, Descripcion = "FCE Factura MiPyMEs C", CodigoArca = ComprobanteTipo.FCE_FACTURA_MIPYMES_C_CODIGO_AFIP, Letra = ComprobanteTipo.FCE_FACTURA_MIPYMES_C_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = "FCEC" },
new ComprobanteTipo() { Idm = ComprobanteTipo.FCE_NOTA_DEBITO_MIPYMES_C, Descripcion = "FCE Nota de Dédito MiPyMEs C", CodigoArca = ComprobanteTipo.FCE_NOTA_DEBITO_MIPYMES_C_CODIGO_AFIP, Letra = ComprobanteTipo.FCE_NOTA_DEBITO_MIPYMES_C_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = "NDEC" },
new ComprobanteTipo() { Idm = ComprobanteTipo.FCE_NOTA_CREDITO_MIPYMES_C, Descripcion = "FCE Nota de Crédito MiPyMEs C", CodigoArca = ComprobanteTipo.FCE_NOTA_CREDITO_MIPYMES_C_CODIGO_AFIP, Letra = ComprobanteTipo.FCE_NOTA_CREDITO_MIPYMES_C_CODIGO_LETRA, TipoOperacion = -1, DescAbreviada = "NCEC" },
new ComprobanteTipo() { Idm = ComprobanteTipo.DIF_CAMBIO_F_MAS, Descripcion = "Dif Cambio F (+)", CodigoArca = ComprobanteTipo.DIF_CAMBIO_F_MAS_CODIGO_AFIP, Letra = ComprobanteTipo.DIF_CAMBIO_F_MAS_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = "DCF+" },
new ComprobanteTipo() { Idm = ComprobanteTipo.DIF_CAMBIO_F_MENOS, Descripcion = "Dif Cambio F (-)", CodigoArca = ComprobanteTipo.DIF_CAMBIO_F_MENOS_CODIGO_AFIP, Letra = ComprobanteTipo.DIF_CAMBIO_F_MENOS_CODIGO_LETRA, TipoOperacion = -1, DescAbreviada = "DCF-" },
new ComprobanteTipo() { Idm = ComprobanteTipo.DIF_CAMBIO_R_MAS, Descripcion = "Dif Cambio R (+)", CodigoArca = ComprobanteTipo.DIF_CAMBIO_R_MAS_CODIGO_AFIP, Letra = ComprobanteTipo.DIF_CAMBIO_R_MAS_CODIGO_LETRA, TipoOperacion = 1, DescAbreviada = "DCR+" },
new ComprobanteTipo() { Idm = ComprobanteTipo.DIF_CAMBIO_R_MENOS, Descripcion = "Dif Cambio R (-)", CodigoArca = ComprobanteTipo.DIF_CAMBIO_R_MENOS_CODIGO_AFIP, Letra = ComprobanteTipo.DIF_CAMBIO_R_MENOS_CODIGO_LETRA, TipoOperacion = -1, DescAbreviada = "DCR-" },
new ComprobanteTipo() { Idm = ComprobanteTipo.ESTADO_CUENTA, Descripcion = "Estado de Cuenta", CodigoArca = ComprobanteTipo.ESTADO_CUENTA_CODIGO_AFIP, Letra = ComprobanteTipo.ESTADO_CUENTA_CODIGO_LETRA, TipoOperacion = 0, DescAbreviada = "EDCC" },
new ComprobanteTipo() { Idm = ComprobanteTipo.ORDEN_PAGO, Descripcion = "Orden de Pago", CodigoArca = ComprobanteTipo.ORDEN_PAGO_CODIGO_AFIP, Letra = ComprobanteTipo.ORDEN_PAGO_CODIGO_LETRA, TipoOperacion = 0, DescAbreviada = "OP" },
new ComprobanteTipo() { Idm = ComprobanteTipo.CERTIFICADO, Descripcion = "CERTIFICADO", CodigoArca = ComprobanteTipo.CERTIFICADO_CODIGO_AFIP, Letra = ComprobanteTipo.CERTIFICADO_CODIGO_LETRA, TipoOperacion = 0, DescAbreviada = "CERT" },
new ComprobanteTipo() { Idm = ComprobanteTipo.COTIZACION_ETIQUETAS, Descripcion = "Cotización Etiquetas", CodigoArca = ComprobanteTipo.COTIZACION_ETIQUETAS_CODIGO_AFIP, Letra = ComprobanteTipo.COTIZACION_ETIQUETAS_CODIGO_LETRA, TipoOperacion = 0, DescAbreviada = "COTE" }
        );
    }

}
